name: Rule Validation CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  validate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: Transpile Schematron to XSL per phase (rule)
        run: scripts/transpile_phases.sh

      - name: Perform validation of template XMLs against phase XSL
        run: scripts/validate_templates.sh

      - name: Upload validation results
        uses: actions/upload-artifact@v4
        with:
          name: rule-validation-results
          path: validation_output

      - name: Validate whether failing tests fail and passing test pass
        run: scripts/validate_output.sh
