name: Rule Validation CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  validate-rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependencies
        run: scripts/install_dependencies.sh

      - name: Transpile phases to XSL
        run: scripts/transpile_phases.sh

      - name: Validate templates
        run: scripts/validate_templates.sh

      - name: Upload validation reports
        uses: actions/upload-artifact@v4
        with:
          name: rule-validation-reports
          path: validation_output

      - name: Validate test reports
        run: scripts/validate_output.sh
